destination/urls.py
from django.conf.urls import url
from .views import destination_search_page, beach_details, get_beach_name, get_beach, getInformation, get_beach_by_name, get_beach_map, get_beach_by_category

urlpatterns = [
    url(r'^$', destination_search_page, name='destination-search-page'),
    url(r'^get/beach/name/', get_beach_name, name='get-beach-name'),
    url(r'^(?P<id>\d)/get/beach/map/(?P<tipe>.*)/(?P<name>.*)/', get_beach_map, name='get-beach-map'),
    url(r'^get/(?P<beach_name>.*)/information/', get_beach, name='get-beach'),
    url(r'^(?P<id>\d)/get/beach/information/', getInformation, name='get-information'),
    url(r'^(?P<id>\d)/', beach_details, name='beach-details'),
    url(r'^get/(?P<nama_pantai>.*)/', get_beach_by_name, name='get-beach-by-name'),
    url(r'^find/category/(?P<kategori_pantai>.*)/', get_beach_by_category, name='get-beach-by-category'),
]

home/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

kepantai/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import destination.urls as destination
import transportation.urls as transportation
import home.urls as home
import review.urls as review
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^destination/', include(destination,namespace='destination')),
    url(r'^transportation/', include(transportation,namespace='transportation')),
    url(r'^home/', include(home,namespace='home')),
    url(r'^review/', include(review,namespace='review')),
    url(r'^$', RedirectView.as_view(permanent=True, url='/home/'), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

transportation/urls.py
from django.conf.urls import url
from .views import transportation_page,map_util

urlpatterns = [
    url(r'^$', transportation_page, name='transportation_page'),
    url(r'util/$', map_util, name='map_util'),
]

destination/models.py
from django.db import models

# Create your models here.

class Beach(models.Model):
    name = models.CharField(max_length=140, blank=False)

    description = models.TextField()
    location_description = models.TextField()
    activities = models.TextField()
    event_and_festival = models.TextField()
    price = models.TextField()
    beach_category = models.TextField()
    frame_location = models.CharField(max_length=140, blank=False)

    display_picture = models.CharField(max_length=140, blank=False)
    cover_picture = models.CharField(max_length=140, blank=False)
    class Meta:
        ordering = ('name', 'id')

class Review(models.Model):
    user_name = models.CharField(max_length=140, blank=False)
    user_from = models.CharField(max_length=140, blank=False)
    beach_name = models.CharField(max_length=140, blank=False)
    content = models.TextField()
    rating = models.CharField(max_length=140, blank=False)
    picture = models.CharField(max_length=140, blank=False)

    profile_picture = models.CharField(max_length=140, blank=False)

# class Category(models.Model):
#     category_name = models.CharField(max_length=140, blank=False)
#     member = models.ForeignKey(Beach)

class MapCollection(models.Model):
    beach_name = models.CharField(max_length=140, blank=False)
    tipe = models.CharField(max_length=140, blank=False)
    url = models.CharField(max_length=140, blank=False)

class Photos(models.Model):
    beach_name = models.CharField(max_length=140, blank=False)
    picture = models.CharField(max_length=140, blank=False)

home/models.py
from django.db import models

# Create your models here.

review/models.py
from django.db import models

# Create your models here.

transportation/models.py
from django.db import models

# Create your models here.

destination/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Beach, Photos, Review, MapCollection
from django.core import serializers
import json, ast

# Create your views here.
response = {}
def destination_search_page(request):
    if 'category_flag' in request.session:
        html = 'destination_search_page.html'
        del request.session['category_flag']
        return render(request, html, response)
    else:
        list_beach = Beach.objects.all()
        response['list_beach'] = list_beach
        html = 'destination_search_page.html'
        return render(request, html, response)

def beach_details(request, id):
    beach = Beach.objects.get(pk=id)
    beach_name = beach.name
    print(beach_name)
    list_photo = Photos.objects.filter(beach_name=beach_name)
    print(list_photo)
    review = Review.objects.get(beach_name=beach_name)
    print(review)
    response['review'] = review
    response['list_photo'] = list_photo
    response['beach'] = beach
    html = 'beach_details.html'
    return render(request, html, response)

def get_beach_name(request):
    data = Beach.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type="application/json")

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

def getInformation(request, id):
    beach = Beach.objects.get(pk=id)
    information = beach.location_description
    beach = model_to_dict(beach)
    beach = ast.literal_eval(beach)
    return JsonResponse(beach)

def get_beach(request, beach_name):
    beach = Beach.objects.get(name=beach_name)
    # print(beach.pk)
    beach = model_to_dict(beach)
    beach = ast.literal_eval(beach)
    return JsonResponse(beach)

def get_beach_by_name(request, nama_pantai):
    if nama_pantai == "all":
        beach = Beach.objects.all()
        response['list_beach'] = beach
        response['single_beach'] = 0
        if 'single_beach' in request.session:
            del request.session['single_beach']
        return redirect(reverse('destination:destination-search-page'))
    else:
        beach = Beach.objects.get(name=nama_pantai)
        response['single_beach'] = 1
        response['beach'] = beach
        # request.session['flag'] = "single"
        return redirect(reverse('destination:destination-search-page'))

def get_beach_by_category(request, kategori_pantai):
    beach = Beach.objects.filter(beach_category__contains=kategori_pantai)
    # for i in beach:
    #     print(i.name)
    if beach.count()>1:
        response['list_beach'] = beach
        print(response['list_beach'])
        request.session['category_flag'] = 1
        response['single_beach'] = 0
        # if 'single_beach' in request.session:
        #     del request.session['single_beach']
        return redirect(reverse('destination:destination-search-page'))
    else:
        response['beach'] = beach.first()
        response['single_beach'] = 1
        return redirect(reverse('destination:destination-search-page'))
    # # print(beach)
    # if 'single_beach' in request.session:
    #     del request.session['single_beach']

    # if beach.count()>1:
    #     print("banyak")
    #     response['single_beach']=0
    #     response['list_beach'] = beach
    # else :
    #     print("satu")
    #     response['single_beach']=0
    #     response['beach'] = beach
    # return redirect(reverse('destination:destination-search-page'))
    #
def get_beach_map(request, id, tipe, name):
    # beach_target = Beach.objects.get(pk=id)
    # beach_name = beach_target.name
    beach = MapCollection.objects.get(beach_name=name, tipe=tipe)
    print("tipe " + tipe)
    print("beach " + beach.url)
    # print("test")
    # url = url.url
    return HttpResponse(beach.url)

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	response = {}
	return render(request, 'home.html', response)

review/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	response = {}
	return render(request, 'review.html', response)

transportation/views.py
from django.shortcuts import render, redirect, reverse
from django.http import (HttpResponse, HttpResponseRedirect)

# Create your views here.

response = {}
def transportation_page(request):
	html = 'transportation.html'
	return render(request, html, response)

def map_util(request):
	html = 'util.html'
	return render(request, html , response)

destination/templates/beach_details.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
Find destination
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/beach_details.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/font/flaticon.css' %}" />
{% endblock %}

{% block content %}
<header id="cover" style="background-image: url('{{beach.cover_picture}}')">
  <p hidden id="beach-name-hidden">{{beach.name}}</p>
  <h1 id="beach-name">{{beach.name}} Beach</h1>
  <p id="id-beach" hidden>{{beach.pk}}</p>
</header>

<section id="explanation">
  <div class="container">
    <div class="row">
        <div class="col-md-5 col-lg-4" id="description-column">
        {% for photo in list_photo %}
          <img src="{{photo.picture}}" alt="" id="more-photo">
        {% endfor %}
      </div>
        <div class="col-md-7 col-lg-8" id="description-column">
        <h1 id="explanation-title">DESCRIPTION</h1>
        <div class="row" id="column">
            <a href="#a" id="location-a">LOCATION</a>
            <a href="#a" class="each-column" id="activities-a">ACTIVITIES</a>
            <a href="#a" class="each-column" id="event-and-festival-a">EVENT & FESTIVALS</a>
            <a href="#a" class="each-column" id="price-a">PRICE</a>
        </div>
        <div id="description-content">
          <div>
            <p id="content">{{beach.location_description}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="advance-information">
  <div class="container" id="">
    <div class="row">
      <div class="col-md-2" id="advance-information-icon">
        <a href="#a" class="advance-information" id="route-a">
          <i class="flaticon-distance-to-travel-between-two-points"></i>
          <br>
          <p id="startRoute">ROUTE</p>
        </a>
        <a href="#a" class="advance-information" id="transportation-a">
          <i class="flaticon-transport"></i>
          <br>
          <p>TRANSPORTATION</p>
        </a>
        <a href="#a" class="advance-information" id="souvenirs-a">
          <i class="flaticon-store"></i>
          <br>
          <p>SOUVENIRS</p>
        </a>
        <a href="#a" class="advance-information" id="restaurant-a">
          <i class="flaticon-dinner"></i>
          <br>
          <p>RESTAURANT</p>
        </a>
        <a href="#a" class="advance-information" id="accomodation-a">
          <i class="flaticon-hotel-building"></i>
          <br>
          <p>ACCOMODATION</p>
        </a>
        <a href="#a" class="advance-information" id="real-time-a">
          <i class="flaticon-eye"></i>
          <br>
          <p>REAL TIME</p>
        </a>
      </div>
      <div class="col-md-10" id="map">
          <iframe src="{{beach.frame_location}}" width="100%" height="596px" style="border:none;"></iframe>
      </div>
    </div>
  </div>
</section>

<section id="review">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="row" id="profile-review">
          <div class="col-md-6" style="padding: 0;">
            <img src="{{review.profile_picture}}" alt="" id="profile-picture" style="float: left">
          </div>
          <div class="col-md-6" style="padding: 0;" id="review-user-data">
            <h5 id="review-name">{{review.user_name}}</h5>
            <p style="margin-bottom: 1%;">from {{review.user_from}}</p>
            <p>{{review.rating}} / 5</p>
          </div>
        </div>
        <div class="row">
          <h5 style="margin-top: 5%;" id="review-beach-name">{{review.beach_name}}</h5>
          <p id="review-content">"{{review.content}}"</p>
        </div>
      </div>
      <div class="col-md-7">
        <img src="{{review.picture}}" alt="" style="border: 5px solid white;" id="review-image">
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block javascript %}
  <!-- javascript beach_details -->
  <script type="text/javascript" src="{% static 'js/dataPantai.json' %}"></script>
  <script type="text/javascript" src="{% static 'js/map.js' %}"></script>
  <script src="{% static 'js/beach_details.js' %}"></script>


  <script async defer
    src="https://maps.googleapis.com/maps/api/js?v=3.30
        &key=AIzaSyCL80yP6FbvN-vz-HMqbeFbpId68_azpYk&libraries=places"></script>
{% endblock %}

destination/templates/destination_search_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
Find destination
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/destination.css' %}" />
{% endblock %}

{% block content %}
<section class="container">
  <h1 id="page-title">DESTINATIONS</h1>

  <nav id="dropdown-section">
    <nav class="row">
      <nav class="col-md-6 col-xl-6">
        <select class="" name="" id="beach-name-selection">
          <option value="">Select by name</option>
          <option value="all">All Beach</option>
        </select>
      </nav>
    </nav>
    <nav class="row">
      <nav class="col-md-6 col-xl-6">
        <select class="" name="" id="beach-category-selection">
          <option value="">Search by category</option>
          <option value="Legend">Legend</option>
          <option value="Ritual">Ritual</option>
          <option value="Camp">Camp</option>
          <option value="Fishing">Fishing</option>
        </select>
      </nav>
    </nav>
  </nav>

  <nav id="content-section">
    {% if single_beach > 0 %}
      <nav class="row">
        <nav class="col-md-6" id="picture-section">
          <img src="{{beach.display_picture}}" alt="" id="each-beach-picture">
        </nav>
        <nav class="col-md-6" id="picture-explanation">
          <h2 id="beach-name">{{beach.name}} Beach</h2>
          <p id="beach-description">{{beach.description}}</p>
          <a href="{% url 'destination:beach-details' beach.id %}" id="button-more" class="btn">KNOW MORE</a>
        </nav>
      </nav>
    {% else %}
      {% for beach in list_beach %}
        <nav class="row">
          <nav class="col-md-6" id="picture-section">
            <img src="{{beach.display_picture}}" alt="" id="each-beach-picture">
          </nav>
          <nav class="col-md-6" id="picture-explanation">
            <h2 id="beach-name">{{beach.name}} Beach</h2>
            <p id="beach-description">{{beach.description}}</p>
            <a href="{% url 'destination:beach-details' beach.id %}" id="button-more" class="btn">KNOW MORE</a>
          </nav>
        </nav>
        <hr>
      {% endfor %}
    {% endif %}
  </nav>

</section>
{% endblock %}

{% block javascript %}
  <!-- javascript destination_search_page -->
  <script src="{% static 'js/destination_search_page.js' %}"></script>
{% endblock %}

home/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
KePantai
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
{% endblock %}

{% block content %}
<section name="home-intro" id="home-intro">
  <div class="back-pic" style="background-image:url(https://3.bp.blogspot.com/-Q4ChrWgqK50/V-tj-H9q3EI/AAAAAAAAEC8/_hP8U1AemM4ef3aXp7XM2Wd_go913vtOwCEw/s1600/Pantai%2BNglambor%2BLokasi.jpg); background-size: cover; height:100%; width: 100%;">
		<div class="container py-5 text-center">
      <div class="row">
        <div class="col-md-12 text-white">
          <h1 class="display-1" id="home-head">DISCOVER</h1>
          <p class="lead mb-5" id="home-desc">WONDERFUL BEACH IN JOGJAKARTA</p>
          <a href="{% url 'destination:destination-search-page' %}">
          	<img class="go-explore" src="{% static 'image/logo.png' %}">
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

<section name="web-desc" id="web-desc">
	<br>
	<h1 id="webdesc-head" align="center" style="color: #000080; padding-bottom: 50px">WHY USE THIS WEBSITE</h1>
    <div class="container">
    <div class="box box-1">
      <div class="box1-kanan">
          <img class="logo-desc" src="{% static 'image/logo2.png' %}" style="float: right;">
      </div>
      <div class="box1-kiri">
        <h2 id="webdesc-detail">EASY TO USE</h2>
          <p class="">Simple design won't make you confused to get an information abut beach tourisms in Yogyakarta.</p>
      </div>
    </div>
</div>
    <div class="container">
    <div class="box box-2" style="padding-left: 25%">
      <div class="box2-kiri">
        <h2 id="webdesc-detail" align="right">UP TO DATE INFORMATIONS</h2>
          <p class="" align="right">The latest information about beach tourism in Yogyakarta will give you trusted information.</p>
      </div>
      <div class="box2-kanan">
        <img class="logo-desc" src="{% static 'image/logo3.png' %}" style="float: left;">
      </div>
    </div>
<div class="container">
    <div class="box box-3">
      <div class="box1-kanan">
          <img class="logo-desc" src="{% static 'image/logo4.png' %}" style="float: right;">
      </div>
      <div class="box1-kiri">
        <h2 id="webdesc-detail">COMPLETE INFORMATIONS</h2>
          <p class="">You can get all informations about beach tourisms in Yogyakarta.</p>
        </div>
      </div>
    </div>
  </div>
    <div class="container">
    <div class="box box-4" style="padding-left: 25%">
      <div class="box2-kiri">
        <h2 id="webdesc-detail" align="right">REAL TRAVELER REVIEWS</h2>
          <p class="" align="right">Verified reviews who went to the beach in Yogyakarta will help you make the right decisions.</p>
      </div>
      <div class="box2-kanan">
          <img class="logo-desc" src="{% static 'image/logo5.png' %}" style="float: left;">
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block javascript %}
<script>
  $.fn.extend({
    animateCss: function (animationName) {
        var animationEnd = 'webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend';
        this.addClass('animated ' + animationName).one(animationEnd, function() {
            $(this).removeClass('animated ' + animationName);
        });
        return this;
    }
});


var flag1 = false;
var flag2 = false;
var flag3 = false;
var flag4 = false;

window.addEventListener("scroll", Animation);
function Animation()
{

  var box1 = $('.box-1');
  var box2 = $('.box-2');
  var box3 = $('.box-3');
  var box4 = $('.box-4');

  
  var isElementInView1 = Utils.isElementInView(box1, false);
  var isElementInView2 = Utils.isElementInView(box2, false);
  var isElementInView3 = Utils.isElementInView(box3, false);
  var isElementInView4 = Utils.isElementInView(box4, false);


  if(flag1 != isElementInView1) {
    flag1 = isElementInView1
    if(flag1 == true){
      box1.animateCss('animated fadeInRight');
    }
  }

  if(flag2 != isElementInView2) {
    flag2 = isElementInView2
    if(flag2 == true){
      box2.animateCss('animated fadeInLeft');
    }
  }

  if(flag3 != isElementInView3) {
    flag3 = isElementInView3
    if(flag3 == true){
      box3.animateCss('animated fadeInRight');
    }
  }

  if(flag4 != isElementInView4) {
    flag4 = isElementInView4
    if(flag4 == true){
      box4.animateCss('animated fadeInLeft');
    }
  }
}

function Utils() {

}

Utils.prototype = {
    constructor: Utils,
    isElementInView: function (element, fullyInView) {
        var pageTop = $(window).scrollTop();
        var pageBottom = pageTop + $(window).height();
        var elementTop = $(element).offset().top;
        var elementBottom = elementTop + $(element).height();

        if (fullyInView === true) {
            return ((pageTop < elementTop) && (pageBottom > elementBottom));
        } else {
            return ((elementTop <= pageBottom) && (elementBottom >= pageTop));
        }
    }
};

var Utils = new Utils();
</script>
{% endblock %}

review/templates/review.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Review
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/review.css' %}" />
{% endblock %}

{% block content %}
<section>
	<div class="container" style="margin-top: 20px">
		<h1 style="margin-bottom: 0px">REVIEW COLUMN</h1>
		<p>GIVE SOME REVIEW OF YOUR ADVENTURE!</p>
		<form class="review-form">
            <div class="form-group"> <label for="InputName">Name</label>
              <input type="text" class="form-control" id="InputName" placeholder="Name"> </div>
            <div class="form-group"> <label for="InputEmail1">From</label>
              <input type="email" class="form-control" id="InputEmail1" placeholder="From"> </div>
            <div class="form-group"> <label for="InputEmail1">Where did you go?</label><br>
              <select>
				  <option value="Beach1">Parangtritis Beach</option>
				  <option value="Beach2">Goa Cemara Beach</option>
				  <option value="Beach3">Baron Beach</option>
				  <option value="Beach4">Sadeng Beach</option>
				  <option value="Beach5">Glagah Beach</option>
				</select>
			</div>
            <div class="form-group"> <label for="Textarea">Review</label> <textarea class="form-control" id="Textarea" rows="4" placeholder="Your review"></textarea> </div>
            <button type="submit" class="btn btn-secondary" onclick="myFunction()">Submit</button>
          </form>
	</div>
</section>
<br>

<section id="review">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="row" id="profile-review">
          <div class="col-md-6" style="padding: 0;">
            <img src="https://kepantai.herokuapp.com/media/goacemara/anon4.jpg" alt="" id="profile-picture" style="float: left">
          </div>
          <div class="col-md-6" style="padding: 0;" id="review-user-data">
            <h5 id="review-name">Harry</h5>
            <p style="margin-bottom: 1%;">from Singapore</p>
            <p>4 / 5</p>
          </div>
        </div>
        <div class="row">
          <h5 style="margin-top: 5%;" id="review-beach-name">Goa Cemara Beach</h5>
          <p id="review-content">"Gonna switched to 4 wheel to get here. The ride is extremly long and bumpy. So mch so u feel like throwing out. After watching running man, well.. thanks to Lee Gwang Soo. I told myself I must try this! We reached in the evening. My driving literally sped to get us to destination. So much so we have to skip lunch. Sunser was lovely, that i have to admit! I love the sound of the waves and the wind slapping on my cheeks for sure!"</p>
        </div>
      </div>
      <div class="col-md-7">
        <img src="https://kepantai.herokuapp.com/media/goacemara/review_goacemara.jpg" alt="" style="border: 5px solid white;" id="review-image">
      </div>
    </div>
  </div>
</section>
<!-- <section class="review user" style="background-color: #000080">
	<div class="container">
		<div class="row">
			<div class="col-left" align="middle" style="color: white">
				<h2>LUCAS HANSEL</h2>
				<h4>Canada</h4>
			</div>
			<div class="col-right">
				
			</div>
		</div>
	</div>
</section> -->
{% endblock %}

{% block javascript %}
<script type="text/javascript">
	function myFunction(){
		alert('Thank you for taking your time for the review.')
		location.reload()
	}
</script>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static 'image/icon.png'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" integrity="  sha384-OHBBOqpYHNsIqQy8hL1U+8OXf9hH6QRxi0+EODezv82DfnZoV7qoHAZDwMwEJvSw" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <title>
      {% block title %}
      <!-- Title masing2 page bedaiin -->
      {% endblock %}
    </title>
      {% block css %}
      <!-- CSS TAROH DI APPS MASING2 AJA YA BUAT NYESUAIIN -->
      {% endblock %}
</head>

<body >
    <header>
      {% include "partials/header.html" %}
    </header>

    <content>
      {% block content %}

      {% endblock %}
    </content>

    <footer>
      {% include "partials/footer.html" %}
    </footer>
</body>

<!-- Bootstrap n JQuery Script -->
<!-- <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script> -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
{% block javascript %}
<!-- BUAT NAMBAHIN SCRIPT -->
{% endblock %}
</html>

templates/partials/header.html
{% load static %}
<style media="screen">
  .navbar{
    height: 50px;
    background-color: #000080;	
  }
  .navbar-light .navbar-nav .active>.nav-link, .navbar-light .navbar-nav .nav-link.active, .navbar-light .navbar-nav .nav-link.open, .navbar-light .navbar-nav .open>.nav-link {
    color: white;
  }
  .navbar-light .navbar-nav .nav-link {
    color: white;
}

@media only screen and (max-width: 768px){
  .navbar-nav{
    background-color: white;
  }
  .navbar-light .navbar-nav .nav-link {
    color: black;
}

}
</style>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="z-index: 1;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a href="{% url 'home:index' %}"><img src="{% static 'image/kepantai.png'%}" width="150" height="40" class="d-inline-block align-top" alt=""> </a>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'destination:destination-search-page' %}">Destination</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'transportation:transportation_page' %}">Transportation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'review:index' %}">Review</a>
      </li>
      <li class="nav-item" style="margin-left: 10px; padding-top: 5px" >
        <a href="#"><img src="{% static 'image/indoflag.png' %}" width="40" height="30" title="Bahasa Indonesia"></a>
      </li>
    </ul>
<!--     <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
</div>
</nav>